/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clasess.Create_Backup;
import Clasess.DB_connection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class Vehicle extends javax.swing.JFrame {

    Date d;
    SimpleDateFormat sdf;
    String stfid;
    String type;
    /**
     * Creates new form suppliers
     */
    public Vehicle() {
        initComponents();
        loadsup();
        load_time_and_date();
        setExtendedState(MAXIMIZED_BOTH);
        exit.setContentAreaFilled(false);
        Minimize.setContentAreaFilled(false);
        jScrollPane2.setVisible(false);
        jScrollPane4.setVisible(false);
        engno.grabFocus();

        setYear();

    }

    Vehicle(String s,String t) {
         initComponents();
        loadsup();
        load_time_and_date();
        setExtendedState(MAXIMIZED_BOTH);
        exit.setContentAreaFilled(false);
        Minimize.setContentAreaFilled(false);
        jScrollPane2.setVisible(false);
        jScrollPane4.setVisible(false);
        engno.grabFocus();

        setYear();
        stfid=s;
        staff.setText(s);
        type=t;
        
                this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        engno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        chasno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        type1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        engcap = new javax.swing.JTextField();
        col = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        date = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        time = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        staff = new javax.swing.JLabel();
        staffid = new javax.swing.JLabel();
        Minimize = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        model = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        manu = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        cost = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        did = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jLabel18 = new javax.swing.JLabel();
        sellpri = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Engine No");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 90, -1));

        engno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engnoActionPerformed(evt);
            }
        });
        engno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                engnoKeyReleased(evt);
            }
        });
        jPanel1.add(engno, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 180, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Chasis No");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, -1, -1));

        chasno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chasnoActionPerformed(evt);
            }
        });
        jPanel1.add(chasno, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 150, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("Model");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 250, 60, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("Type");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 250, -1, -1));

        type1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type1ActionPerformed(evt);
            }
        });
        jPanel1.add(type1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 250, 130, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("Engine capacity");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 250, -1, -1));

        engcap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engcapActionPerformed(evt);
            }
        });
        engcap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                engcapKeyTyped(evt);
            }
        });
        jPanel1.add(engcap, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 250, 100, -1));

        col.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colActionPerformed(evt);
            }
        });
        jPanel1.add(col, new org.netbeans.lib.awtextra.AbsoluteConstraints(1610, 250, 180, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton1.setText("Register and buy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 160, 30));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rsz_77002-200.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 50, 50));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, 90, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 80, 30));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 80, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dealer-logo.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 180));

        jPanel2.setBackground(new java.awt.Color(255, 255, 251));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 153, 255)));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(255, 255, 253));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Engine No", "Chasis No", "Eng_Capacity", "Model", "Type", "Color", "Manufacture", "Year", "Date of baught", "Cost", "Selling Price", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setFocusable(false);
        jTable1.setGridColor(new java.awt.Color(255, 255, 251));
        jTable1.setInheritsPopupMenu(true);
        jTable1.setName(""); // NOI18N
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getAccessibleContext().setAccessibleName("");
        jTable1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1774, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 1800, 400));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Vehicle");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 150, 90, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 1880, 10));

        date.setEditable(false);
        date.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        date.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 100, 110, 30));

        jLabel11.setText("Date");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 100, 40, 30));

        jLabel13.setText("Time");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 60, 40, 30));

        time.setEditable(false);
        time.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        time.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        time.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeActionPerformed(evt);
            }
        });
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 60, 110, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user-icon.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1740, 80, 30, 30));
        jPanel1.add(staff, new org.netbeans.lib.awtextra.AbsoluteConstraints(1790, 80, 100, 30));

        staffid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        staffid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fields.png"))); // NOI18N
        jPanel1.add(staffid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1780, 80, 110, 30));

        Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Minimize Window-48.png"))); // NOI18N
        Minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizeActionPerformed(evt);
            }
        });
        jPanel1.add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1820, 10, 30, 30));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close Window-48.png"))); // NOI18N
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1860, 10, 30, 30));

        model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelActionPerformed(evt);
            }
        });
        jPanel1.add(model, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 250, 180, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton5.setText("Clear All");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, -1, 30));

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jList1MouseEntered(evt);
            }
        });
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jList1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 180, 80));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel15.setText("Color");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 250, -1, -1));

        jLabel5.setText("cc");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 250, -1, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setText("Manufacture");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 90, -1));

        manu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manuActionPerformed(evt);
            }
        });
        manu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                manuKeyReleased(evt);
            }
        });
        jPanel1.add(manu, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 180, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel10.setText("Year");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 50, -1));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 150, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel16.setText("Status");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 370, -1, -1));

        cost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costActionPerformed(evt);
            }
        });
        cost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                costKeyTyped(evt);
            }
        });
        jPanel1.add(cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 370, 170, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel17.setText("Cost");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 370, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "On_sale", "Sold", "Recerved" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 370, 150, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel12.setText("Dealer ID");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 370, 70, -1));

        did.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                didActionPerformed(evt);
            }
        });
        did.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                didKeyReleased(evt);
            }
        });
        jPanel1.add(did, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 370, 180, -1));

        jList3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jList3MouseEntered(evt);
            }
        });
        jList3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jList3KeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(jList3);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 390, 180, 80));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel18.setText("Selling Price");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 370, -1, -1));

        sellpri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellpriActionPerformed(evt);
            }
        });
        sellpri.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sellpriKeyTyped(evt);
            }
        });
        jPanel1.add(sellpri, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 370, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void engnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engnoActionPerformed
        // TODO add your handling code here:
        chasno.grabFocus();
        jScrollPane2.setVisible(false);
    }//GEN-LAST:event_engnoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            String s;
            String s2 = (String) jComboBox2.getSelectedItem();

            if ("On_sale".equals(s2)) {
                s = "1";
            } else if ("Sold".equals(s2)) {
                s = "0";
            } else {
                s = "2";
            }

            DB_connection.iud("insert into vehicle (Engine_No, Chasis_No, Eng_Capacity, Model, Type, Color, Manufacture, Year, Date_Of_Baught, Cost, Selling_Price, Status) values ('" + engno.getText() + "', '" + chasno.getText() + "', '" + engcap.getText() + "', '" + model.getText() + "', '" + type1.getText() + "', '" + col.getText() + "','" + manu.getText() + "','" + jComboBox1.getSelectedItem().toString() + "', '" + date.getText() + "', '" + Integer.parseInt(cost.getText()) + "', '" + Integer.parseInt(sellpri.getText()) + "', '" + s + "')");
            DB_connection.iud("insert into grn (Dealer_D_ID, Vehicle_Engine_No, Vehicle_Chasis_No, Date, Time, Cost) values ('"+did.getText()+"', '"+engno.getText()+"', '"+chasno.getText()+"', '"+date.getText()+"', '"+time.getText()+"', '"+cost.getText()+"')");
            
            clearall();

        } catch (com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException ex) {
            JOptionPane.showMessageDialog(this, "This Vehicle already registerd");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void chasnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chasnoActionPerformed
        // TODO add your handling code here:
        engcap.grabFocus();
    }//GEN-LAST:event_chasnoActionPerformed

    private void type1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type1ActionPerformed
        // TODO add your handling code here:
        col.grabFocus();
    }//GEN-LAST:event_type1ActionPerformed

    private void engcapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engcapActionPerformed
        // TODO add your handling code here:
        model.grabFocus();
    }//GEN-LAST:event_engcapActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            DB_connection.iud("delete from vehicle where Engine_No = '" + engno.getText() + "'");

            clearall();
        } catch (Exception e) {
            e.printStackTrace(); 
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {

            String s;
            String s2 = (String) jComboBox2.getSelectedItem();

            if ("On_sale".equals(s2)) {
                s = "1";
            } else if ("Sold".equals(s2)) {
                s = "0";
            } else {
                s = "2";
            }

            DB_connection.iud("Update vehicle set Chasis_No = '" + chasno.getText() + "', Eng_Capacity = '" + engcap.getText() + "', Model = '" + model.getText() + "', Type = '" + type1.getText() + "', Color = '" + col.getText() + "', Manufacture = '" + manu.getText() + "', Year = '" + jComboBox1.getSelectedItem().toString() + "', Cost = '" + cost.getText() + "', Selling_Price = '" + sellpri.getText() + "', Status = '" + s + "' where Engine_No = '" + engno.getText() + "'");
            DB_connection.iud("Update grn set Vehicle_Chasis_No = '" + chasno.getText() + "', Cost = '" + cost.getText() + "', where Engine_No = '" + engno.getText() + "'");
            clearall();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeActionPerformed

    private void MinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizeActionPerformed
        try {
            this.setState(ICONIFIED);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_MinimizeActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        Create_Backup.make_backup();
        try {
            System.exit(0);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_exitActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        //Vector v =new Vector();
        //DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        int i = jTable1.getSelectedRow();
        engno.setText((String) jTable1.getValueAt(i, 0));
        chasno.setText((String) jTable1.getValueAt(i, 1));
        engcap.setText((String) jTable1.getValueAt(i, 2));
        model.setText((String) jTable1.getValueAt(i, 3));
        type1.setText((String) jTable1.getValueAt(i, 4));
        col.setText((String) jTable1.getValueAt(i, 5));
        manu.setText((String) jTable1.getValueAt(i, 6));
        jComboBox1.setSelectedItem((String) jTable1.getValueAt(i, 8));
        cost.setText((String) jTable1.getValueAt(i, 9));
        sellpri.setText((String) jTable1.getValueAt(i, 10));
        jComboBox2.setSelectedItem((String) jTable1.getValueAt(i, 11));


    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if ("".equals(engno.getText())) {
            JOptionPane.showMessageDialog(this, "Input Engine number to search");
        } else {
            search();
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void colActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colActionPerformed
        manu.grabFocus();
    }//GEN-LAST:event_colActionPerformed

    private void modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelActionPerformed
        type1.grabFocus();
    }//GEN-LAST:event_modelActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        clearall();
        engno.grabFocus();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void engnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_engnoKeyReleased
        try {
            if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                jList1.grabFocus();
                jList1.setSelectedIndex(0);
            } else if (engno.getText().equals("")) {
                jScrollPane2.setVisible(false);
            } else {
                ResultSet rs = DB_connection.search("select * from vehicle where Engine_No like '%" + engno.getText() + "%'");
                Vector v = new Vector();
                while (rs.next()) {
                    v.add(rs.getString("Engine_No"));
                }
                jList1.setListData(v);
                if (v.equals("")) {
                    jScrollPane2.setVisible(false);
                }
                jScrollPane2.setVisible(true);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_engnoKeyReleased

    private void jList1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyReleased
        if (evt.getKeyCode() == 10) {
            engno.setText(jList1.getSelectedValue().toString());
            jScrollPane2.setVisible(false);
            search();
            engno.grabFocus();
        }
    }//GEN-LAST:event_jList1KeyReleased

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        engno.setText(jList1.getSelectedValue().toString());
        jScrollPane2.setVisible(false);
        search();
        engno.grabFocus();
    }//GEN-LAST:event_jList1MouseClicked

    private void jList1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jList1MouseEntered

    private void manuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manuActionPerformed
        jComboBox1.grabFocus();
    }//GEN-LAST:event_manuActionPerformed

    private void manuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_manuKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_manuKeyReleased

    private void costActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costActionPerformed
        jComboBox2.grabFocus();
    }//GEN-LAST:event_costActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed


    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
        System.out.println(evt.getKeyChar());
        if (evt.getKeyChar() == 13) {
            cost.grabFocus();
        }
    }//GEN-LAST:event_jComboBox1KeyPressed

    private void costKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_costKeyTyped

    private void engcapKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_engcapKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_engcapKeyTyped

    private void didActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_didActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_didActionPerformed

    private void didKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_didKeyReleased
        try {
            if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                jList3.grabFocus();
                jList3.setSelectedIndex(0);
            } else if (did.getText().equals("")) {
                jScrollPane4.setVisible(false);
            } else {
                ResultSet rs = DB_connection.search("select * from dealer where D_ID like '%" + did.getText() + "%'");
                Vector v = new Vector();
                while (rs.next()) {
                    v.add(rs.getString("D_ID"));
                }
                jList3.setListData(v);
                if (v.equals("")) {
                    jScrollPane4.setVisible(false);
                }
                jScrollPane4.setVisible(true);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_didKeyReleased

    private void jList3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList3MouseClicked
        did.setText(jList3.getSelectedValue().toString());
        jScrollPane4.setVisible(false);
        search();

    }//GEN-LAST:event_jList3MouseClicked

    private void jList3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jList3MouseEntered

    private void jList3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList3KeyReleased
        if (evt.getKeyCode() == 10) {
            did.setText(jList3.getSelectedValue().toString());
            jScrollPane4.setVisible(false);
            search();
            
        }
    }//GEN-LAST:event_jList3KeyReleased

    private void sellpriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellpriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sellpriActionPerformed

    private void sellpriKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sellpriKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_sellpriKeyTyped

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Menu m = new Menu(stfid, type);
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vehicle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Minimize;
    private javax.swing.JTextField chasno;
    private javax.swing.JTextField col;
    private javax.swing.JTextField cost;
    private javax.swing.JTextField date;
    private javax.swing.JTextField did;
    private javax.swing.JTextField engcap;
    private javax.swing.JTextField engno;
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField manu;
    private javax.swing.JTextField model;
    private javax.swing.JTextField sellpri;
    private javax.swing.JLabel staff;
    private javax.swing.JLabel staffid;
    private javax.swing.JTextField time;
    private javax.swing.JTextField type1;
    // End of variables declaration//GEN-END:variables

    private void loadsup() {

        try {

            jTable1.removeAll();
            jTable1.repaint();
            jTable1.revalidate();

            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.getDataVector().removeAllElements();
            ResultSet sr = DB_connection.search("select * from vehicle");

            while (sr.next()) {

                String s2;
                String s = sr.getString("Status");

                if ("1".equals(s)) {
                    s2 = "On_sale";
                } else if ("0".equals(s)) {
                    s2 = "Sold";
                } else {
                    s2 = "Recerved";
                }

                Vector v = new Vector();

                v.add(sr.getString("Engine_No"));
                v.add(sr.getString("Chasis_No"));
                v.add(sr.getString("Eng_Capacity"));
                v.add(sr.getString("Model"));
                v.add(sr.getString("Type"));
                v.add(sr.getString("Color"));
                v.add(sr.getString("Manufacture"));
                v.add(sr.getString("Year"));
                v.add(sr.getString("Date_Of_Baught"));
                v.add(sr.getString("Cost"));
                v.add(sr.getString("Selling_Price"));
                v.add(s2);

                dtm.addRow(v);
            }
            engno.grabFocus();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void load_time_and_date() {
        Timer t = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                d = new Date();
                sdf = new SimpleDateFormat("HH:mm:ss");
                time.setText(sdf.format(d));
                d = new Date();
                sdf = new SimpleDateFormat("YYYY/MM/dd");
                date.setText(sdf.format(d));

            }
        });
        t.start();
    }

    private void clearall() {
        engno.setText(null);
        chasno.setText(null);
        engcap.setText(null);
        model.setText(null);
        col.setText(null);
        type1.setText(null);
        manu.setText(null);
        jComboBox1.setSelectedIndex(0);
        cost.setText(null);
        sellpri.setText(null);
        did.setText(null);
        jComboBox2.setSelectedIndex(0);

        loadsup();
    }

    private void search() {
        try {
            ResultSet rs = DB_connection.search("select * from vehicle where Engine_No = '" + engno.getText() + "'");

            while (rs.next()) {
                chasno.setText(rs.getString("Chasis_No"));
                engcap.setText(rs.getString("Eng_Capacity"));
                model.setText(rs.getString("Model"));
                type1.setText(rs.getString("Type"));
                col.setText(rs.getString("Color"));
                manu.setText(rs.getString("Manufacture"));
                jComboBox1.setSelectedItem(rs.getString("Year"));
                cost.setText(rs.getString("Cost"));
                sellpri.setText(rs.getString("Selling_Price"));

                String s2;
                String s = rs.getString("Status");

                if ("1".equals(s)) {
                    s2 = "On_sale";
                } else if ("0".equals(s)) {
                    s2 = "Sold";
                } else {
                    s2 = "Recerved";
                }

                jComboBox2.setSelectedItem(s2);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void setYear() {

        d = new Date();
        sdf = new SimpleDateFormat("YYYY/MM/dd");

        String s = sdf.format(d);
        int s1 = Integer.parseInt(s.substring(0, 4));
        int s2 = s1 - 30;

        while (s1 >= s2) {
            String p = Integer.toString(s1);
            jComboBox1.addItem(p);

            s1--;
        }

    }

}
